artifacts:
  hazelcast:
    type: hazelcast
    glob_path: ./work/hazelcast*.zip
    repack:
      - delete self:/code-samples
      - delete self:/demo
      - delete self:/docs
    remote_unzip: true

  mysql:
    type: mysql
    glob_path: ./work/mysql-8.0*.tar.gz
    remote_unzip: true
    short_dir_name: true
#    repack:
#        - delete self:/bin/mysqld-debug
#        - delete self:/docs
#        - delete self:/include
#        - delete self:/share
#        - delete self:/support-files
