artifacts:
  mysql:
    type: mysql
    glob_path: ./work/mysql-8.0*.tar.gz
    remote_unzip: true
    short_dir_name: true
    repack:
        - delete: self:/docs
        - delete: self:/include
        - delete: self:/share
        - delete: self:/support-files

